### ISSUE TITLE
new keyring version 23.9.0 breaks the package

### ISSUE THREAD

**Issue by or-asher** [GoogleCloudPlatform/artifact-registry-python-tools#30]
Hey,
ive been using keyrings to auth into GAR for pip installation for a while.
today i set up a venv and started downloading stuff when i ran into this issue
```
ERROR: Error initializing plugin EntryPoint(name='Google Auth', value='keyrings.gauth', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/user/envs/placeholder-venv/lib/python3.8/site-packages/keyring/backend.py", line 202, in _load_plugins
    init_func = ep.load()
  File "/Users/user/envs/placeholder-venv/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 203, in load
    module = import_module(match.group('module'))
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/user/envs/placeholder-venv/lib/python3.8/site-packages/keyrings/gauth.py", line 24, in <module>
    from keyring.util import properties
ImportError: cannot import name 'properties' from 'keyring.util' (/Users/user/envs/placeholder-venv/lib/python3.8/site-packages/keyring/util/__init__.py)

```
after investigating a bit ive found that my previous environments had keyring==23.8.2 which doesnt have the issue.
the code either needs to account for the new version or pin a to previous working version keyring.

**Comment by erdem** [comment]
@rmchale `23.8.2` version worked for me after specifying `keyring` version in the build.

```
pip install keyring==23.8.2
pip install keyrings.google-artifactregistry-auth
```
