### ISSUE TITLE
Issue with latest version of keyring

### ISSUE THREAD

**Issue by Rossco8** [GoogleCloudPlatform/artifact-registry-python-tools#33]
Artifact registry uploads fail with latest version of keyring (23.9) https://pypi.org/project/keyring/

My cloudbuild.yaml has been working for ages without error
```
steps:
  - name: python:3.9
    entrypoint: /bin/bash
    args:
      - -c
      - |
        pip install --upgrade pip setuptools twine wheel
        pip install keyring
        pip install keyrings.google-artifactregistry-auth
        mkdir -p ~/.config/pip
        printf "[distutils]\nindex-servers = \n    ${_REPO}\n\n[${_REPO}]\nrepository: https://${_REGION}-python.pkg.dev/common-source/${_REPO}/\n" > ~/.pypirc
        printf "[global]\nextra-index-url = https://${_REGION}-python.pkg.dev/common-source/${_REPO}/simple/\n" > ~/.config/pip/pip.conf
        python setup.py sdist bdist_wheel
        twine upload --repository-url https://${_REGION}-python.pkg.dev/common-source/${_REPO}/ dist/*
substitutions:
  _REPO: python-common # default value
  _REGION: us # default value
```

The error with latest version of keyring is is
```
ERROR    Error initializing plugin EntryPoint(name='Google Auth',
         value='keyrings.gauth', group='keyring.backends').
         Traceback (most recent call last):
           File "/usr/local/lib/python3.9/site-packages/keyring/backend.py",
         line 202, in _load_plugins
             init_func = ep.load()
           File
         "/usr/local/lib/python3.9/site-packages/importlib_metadata/__init__.py"
         , line 203, in load
             module = import_module(match.group('module'))
           File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in
         import_module
             return _bootstrap._gcd_import(name[level:], package, level)
           File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
           File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
           File "<frozen importlib._bootstrap>", line 986, in
         _find_and_load_unlocked
           File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
           File "<frozen importlib._bootstrap_external>", line 850, in
         exec_module
           File "<frozen importlib._bootstrap>", line 228, in
         _call_with_frames_removed
           File "/usr/local/lib/python3.9/site-packages/keyrings/gauth.py", line
         24, in <module>
             from keyring.util import properties
         ImportError: cannot import name 'properties' from 'keyring.util'
         (/usr/local/lib/python3.9/site-packages/keyring/util/__init__.py)
Traceback (most recent call last):
  File "/usr/local/bin/twine", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/twine/__main__.py", line 33, in main
    error = cli.dispatch(sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/twine/cli.py", line 123, in dispatch
    return main(args.args)
  File "/usr/local/lib/python3.9/site-packages/twine/commands/upload.py", line 198, in main
    return upload(upload_settings, parsed_args.dists)
  File "/usr/local/lib/python3.9/site-packages/twine/commands/upload.py", line 127, in upload
    repository = upload_settings.create_repository()
  File "/usr/local/lib/python3.9/site-packages/twine/settings.py", line 329, in create_repository
    self.username,
  File "/usr/local/lib/python3.9/site-packages/twine/settings.py", line 131, in username
    return cast(Optional[str], self.auth.username)
  File "/usr/local/lib/python3.9/site-packages/twine/auth.py", line 34, in username
    return utils.get_userpass_value(
  File "/usr/local/lib/python3.9/site-packages/twine/utils.py", line 248, in get_userpass_value
    value = prompt_strategy()
  File "/usr/local/lib/python3.9/site-packages/twine/auth.py", line 85, in username_from_keyring_or_prompt
    return self.prompt("username", input)
  File "/usr/local/lib/python3.9/site-packages/twine/auth.py", line 96, in prompt
    return how(f"Enter your {what}: ")
EOFError: EOF when reading a line
ERROR
ERROR: build step 0 "python:3.9" failed: step exited with non-zero status: 1
Enter your username:
```

Reverting to previous version and the uploads work as expected
```
pip install keyring==23.8.2 
```

**Comment by megan-kuo** [comment]
thanks for reaching out, this should be fix with the latest release.
