### ISSUE TITLE
Error "cannot import name 'properties' from 'keyring.util'" with keyring==23.9.0

### ISSUE THREAD

**Issue by looztra** [GoogleCloudPlatform/artifact-registry-python-tools#34]
Since `keyring` version `23.9.0` is out, this backend does not work anymore.

```text
ERROR: Error initializing plugin EntryPoint(name='Google Auth', value='keyrings.gauth', group='keyring.backends').
Traceback (most recent call last):
  File "/home/runner/actions-runner/_work/yolo/yolo/python/moulinette/.tox/linters/lib/python3.9/site-packages/keyring/backend.py", line 202, in _load_plugins
    init_func = ep.load()
  File "/home/runner/actions-runner/_work/yolo/yolo/python/moulinette/.tox/linters/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 203, in load
    module = import_module(match.group('module'))
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/runner/actions-runner/_work/yolo/yolo/python/moulinette/.tox/linters/lib/python3.9/site-packages/keyrings/gauth.py", line 24, in <module>
    from keyring.util import properties
ImportError: cannot import name 'properties' from 'keyring.util' (/home/runner/actions-runner/_work/yolo/yolo/python/moulinette/.tox/linters/lib/python3.9/site-packages/keyring/util/__init__.py)
User for europe-python.pkg.dev: ERROR: Exception:
...
```

**Comment by looztra** [comment]
ok, it seems a bug fix is already on its way, nice! (even before I filled the bug)

https://github.com/GoogleCloudPlatform/artifact-registry-python-tools/commit/0e4aa757bf921a52ec24cc390ead2d75a7e2dee7

**Comment by looztra** [comment]
and it is released https://pypi.org/project/keyrings.google-artifactregistry-auth/#history
and it is a duplicate of #33

sorry, closing

(and thank you)
